[[colors.indexed_colors]]
color = "0xb65611"
index = 16

[[colors.indexed_colors]]
color = "0xd43552"
index = 17

[[colors.indexed_colors]]
color = "0x292824"
index = 18

[[colors.indexed_colors]]
color = "0x6e6b5e"
index = 19

[[colors.indexed_colors]]
color = "0x999580"
index = 20

[[colors.indexed_colors]]
color = "0xe8e4cf"
index = 21

[colors.bright]
black = "0x7d7a68"
blue = "0x6684e1"
cyan = "0x1fad83"
green = "0x60ac39"
magenta = "0xb854d4"
red = "0xd73737"
white = "0xfefbec"
yellow = "0xae9513"

[colors.cursor]
cursor = "0xa6a28c"
text = "0x20201d"

[colors.normal]
black = "0x20201d"
blue = "0x6684e1"
cyan = "0x1fad83"
green = "0x60ac39"
magenta = "0xb854d4"
red = "0xd73737"
white = "0xa6a28c"
yellow = "0xae9513"

[colors.primary]
background = "0x20201d"
foreground = "0xa6a28c"

[font]
size = 14

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
opacity = 0.7
